services:
  go-app:
    build:
      context: ./go
      dockerfile: Dockerfile
    container_name: go_app
    volumes:
      - ../src:/app
    ports:
      - "8080:8080"
      - "2345:2345"
    tty: true

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Asia/Tokyo
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"

volumes:
  postgres_data:
