// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"copilot/internal/adapter/controller"
	"copilot/internal/application/usecase"
	"copilot/internal/infrastructure/config"
	"copilot/internal/infrastructure/db"
	"copilot/internal/infrastructure/repository"
	"copilot/internal/infrastructure/router"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

// Init は依存性注入を使用してgin.Engineを初期化します
func Init() (*gin.Engine, error) {
	configConfig := config.NewConfig()
	bunDB, err := db.NewDB(configConfig)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(bunDB)
	userUseCase := usecase.NewUserUseCase(userRepository)
	userController := controller.NewUserController(userUseCase)
	engine := router.NewRouter(userController)
	return engine, nil
}
