// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"copilot/internal/adapter/controller"
	"copilot/internal/infrastructure/router"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

// Init は依存性注入を使用してgin.Engineを初期化します
func Init() (*gin.Engine, error) {
	userController := controller.NewUserController()
	engine := router.NewRouter(userController)
	return engine, nil
}
