// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"copilot/internal/infrastructure/db"
	"copilot/internal/infrastructure/router"
	"copilot/internal/interface/controller"
	"copilot/internal/interface/repository"
	"copilot/internal/usecase"
)

// InitializeAPI はAPIの依存関係をセットアップする
func InitializeAPI() (*router.Router, error) {
	database := db.NewDB()
	todoRepository := repository.NewTodoRepository(database)
	todoUseCase := usecase.NewTodoUseCase(todoRepository)
	todoController := controller.NewTodoController(todoUseCase)
	routerInstance := router.NewRouter(todoController)
	return routerInstance, nil
}